### PR TITLE
Slovak translation for ETHOS SUITE 1.5.0

### PR DESCRIPTION
**Pull request by brano2378**
Hello,
translation is complette please to integrate

Thanks

### CODE REVIEW

**Comment by bsongis-frsky** [comment]
Would it be possible for you to do the same in the 1.6 branch? I have given WRITE access to you for the Slovak translations, thanks in advance!

**Comment by brano2378** [comment]
Hello,
yes absolutely no problem... Thank you so much for collaborate..

Brano

st 4. 12. 2024 o 13:45 Bertrand Songis @ FrSky ***@***.***>
napísal(a):

**Comment by brano2378** [comment]
Hello Bertrand,

I translate patch1 for merge to suite 1.6.0 I tested locally on my PC works
without problem...

Regards
Brano

št 5. 12. 2024 o 7:51 Brano Mate ***@***.***> napísal(a):

**Comment by brano2378** [comment]
Hello Bertrand,
I finished also with translation for ethos (OS).. it is ready to aplicate..

Brano

št 5. 12. 2024 o 16:37 Brano Mate ***@***.***> napísal(a):

**Pull request merged**
